# Generated by Django 5.2.4 on 2025-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETE', 'COMPLETE')], default='Pending', max_length=20),
        ),
    ]
